export const MOBILE_VERIFICATION_FOR_AGENT = false;
export const MOBILE_VERIFICATION_FOR_HOSPITAL = false;
export const MOBILE_VERIFICATION_FOR_USER = false;
export const MOBILE_VERIFICATION_CODE_LENGTH = 6;